### ISSUE TITLE
Issues with webpack v2.2.1

### ISSUE THREAD

**Issue by girvo** [sairion/buble-loader#30]
With the default config in the README:

```
➜  buble-nodent-webpack ./node_modules/.bin/webpack
/Users/josh/Scratch/buble-nodent-webpack/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/josh/Scratch/buble-nodent-webpack/node_modules/buble/dist/buble.umd.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/josh/Scratch/buble-nodent-webpack/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/josh/Scratch/buble-nodent-webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/josh/Scratch/buble-nodent-webpack/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/Compilation.js:142:10)
    at moduleFactory.create (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/Compilation.js:424:9)
    at /Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/josh/Scratch/buble-nodent-webpack/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/josh/Scratch/buble-nodent-webpack/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/josh/Scratch/buble-nodent-webpack/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
➜  buble-nodent-webpack ./node_modules/.bin/webpack --version
2.2.1
```

Any ideas?

**Comment by mhoyer** [comment]
Well the `README` has a wrong `webpack.config.js` sample when using Webpack 2:

```javascript
module: {
  loaders: [
    {
      test: /.js$/,
      loaders: 'buble', // FAIL
```

Loaders cannot be used with short name anymore. See: https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

Hence, you have to add `-loader`:

```diff
- loaders: 'buble',
+ loaders: 'buble-loader',
```
